# Generated by Django 4.1.5 on 2024-10-09 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, default='profile-image/default.png', null=True, upload_to='profile-image')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('student_number', models.CharField(blank=True, max_length=20, null=True)),
                ('degree', models.CharField(blank=True, choices=[('ปวช.1', 'ปวช.1'), ('ปวช.2', 'ปวช.2'), ('ปวช.3', 'ปวช.3'), ('ปวส.1', 'ปวส.1'), ('ปวส.2', 'ปวส.2')], max_length=10, null=True)),
                ('room', models.CharField(blank=True, max_length=10, null=True)),
                ('department', models.CharField(blank=True, choices=[('ช่างยนต์', 'ช่างยนต์'), ('ช่างกลโรงงาน', 'ช่างกลโรงงาน'), ('ช่างไฟฟ้ากำลัง', 'ช่างไฟฟ้ากำลัง'), ('ช่างเชื่อมโลหะ/เทคนิคโลหะ ', 'ช่างเชื่อมโลหะ/เทคนิคโลหะ'), ('ช่างอิเล็กทรอนิกส์', 'ช่างอิเล็กทรอนิกส์'), ('สถาปัตยกรรม', 'สถาปัตยกรรม'), ('ช่างโยธา', 'ช่างโยธา'), ('เทคโนโลยีสารสนเทศ', 'เทคโนโลยีสารสนเทศ'), ('การบัญชี', 'การบัญชี'), ('การตลาด', 'การตลาด'), ('คอมพิวเตอร์ธุรกิจ', 'คอมพิวเตอร์ธุรกิจ'), ('การเลขานุการ ', 'การเลขานุการ '), ('การจัดการ', 'การจัดการ')], max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('pdpa', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
