# Generated by Django 4.1.5 on 2024-10-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('ช่างยนต์', 'ช่างยนต์'), ('ช่างกลโรงงาน', 'ช่างกลโรงงาน'), ('ช่างไฟฟ้ากำลัง', 'ช่างไฟฟ้ากำลัง'), ('ช่างเทคนิคพลังงาน', 'ช่างเทคนิคพลังงาน'), ('ช่างเชื่อมโลหะ/ซ่อมบำรุง', 'ช่างเชื่อมโลหะ/ซ่อมบำรุง'), ('ช่างเมคคาทรอนิกส์', 'ช่างเมคคาทรอนิกส์'), ('ช่างอิเล็กทรอนิกส์', 'ช่างอิเล็กทรอนิกส์'), ('ช่างสถาปัตยกรรม', 'ช่างสถาปัตยกรรม'), ('ช่างโยธา', 'ช่างโยธา'), ('ช่างก่อสร้าง', 'ช่างก่อสร้าง'), ('เทคโนโลยีธุรกิจดิจิทัล', 'เทคโนโลยีธุรกิจดิจิทัล'), ('เทคโนโลยีสารสนเทศ', 'เทคโนโลยีสารสนเทศ'), ('การบัญชี', 'การบัญชี'), ('การตลาด', 'การตลาด')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
