# Generated by Django 4.1.5 on 2024-10-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_profile_pdpa_remove_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pdpa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
