# Generated by Django 4.1.5 on 2024-10-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='student_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
