# Generated by Django 4.1.5 on 2024-10-11 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_ticket_student_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='website',
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer1', to='activity.organizer'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer2', to='activity.organizer'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer3', to='activity.organizer'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer4', to='activity.organizer'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer5', to='activity.organizer'),
        ),
    ]
