# Generated by Django 4.1.5 on 2024-10-13 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_remove_organizer_website_activity_organizer1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='organizer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer1', to='activity.organizer'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organizer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer2', to='activity.organizer'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organizer3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer3', to='activity.organizer'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organizer4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer4', to='activity.organizer'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organizer5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer5', to='activity.organizer'),
        ),
    ]
