# Generated by Django 4.1.5 on 2024-10-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_organizer1_alter_activity_organizer2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='organizer6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer6', to='activity.organizer'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer7', to='activity.organizer'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer8', to='activity.organizer'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_as_organizer9', to='activity.organizer'),
        ),
    ]
